PREFIX rec: <https://ns.cascadeprotocol.org/records/v1-draft#>
PREFIX jdg: <https://ns.cascadeprotocol.org/judgments/v1-draft#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pav: <http://purl.org/pav/>
PREFIX npx: <http://purl.org/nanopub/x/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX health: <https://ns.cascadeprotocol.org/health/v1#>
PREFIX clinical: <https://ns.cascadeprotocol.org/clinical/v1#>
PREFIX cascade: <https://ns.cascadeprotocol.org/core/v1#>

SELECT ?started ?activityLabel ?recordLabel ?versionLabel ?activity ?revision ?record
WHERE {
  ?activity a prov:Activity ; prov:startedAtTime ?started .
  ?revision prov:wasGeneratedBy ?activity ; rec:revisionOf ?record ; rec:version ?version .
  OPTIONAL { ?activity rdfs:label ?activityLabel }
  OPTIONAL { ?record rdfs:label ?recordLabel }
  OPTIONAL { ?version rdfs:label ?versionLabel }
}
ORDER BY ?started ?recordLabel
