PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label WHERE {
  GRAPH <https://pod.alex-rivera.example/clinical/labels.ttl> { ?one rdfs:label ?label . ?other rdfs:label ?label . FILTER (?one != ?other) }
}
