PREFIX rec: <https://ns.cascadeprotocol.org/records/v1-draft#>
PREFIX jdg: <https://ns.cascadeprotocol.org/judgments/v1-draft#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX pav: <http://purl.org/pav/>
PREFIX npx: <http://purl.org/nanopub/x/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX health: <https://ns.cascadeprotocol.org/health/v1#>
PREFIX clinical: <https://ns.cascadeprotocol.org/clinical/v1#>
PREFIX cascade: <https://ns.cascadeprotocol.org/core/v1#>

CONSTRUCT { ?entry rec:latestMember ?latest }
WHERE {
  { SELECT ?entry (IRI(MIN(STR(?r))) AS ?latest)
    WHERE {
      { SELECT ?entry (MAX(?t2) AS ?t)
        WHERE {
          VALUES ?type2 { health:AllergyRecord health:ConditionRecord health:ImmunizationRecord clinical:Procedure }
          ?r2 a ?type2 ; rec:inEntry ?entry ; rec:currentRevision/prov:generatedAtTime ?t2 . }
        GROUP BY ?entry }
      VALUES ?type { health:AllergyRecord health:ConditionRecord health:ImmunizationRecord clinical:Procedure }
      ?r a ?type ; rec:inEntry ?entry ; rec:currentRevision/prov:generatedAtTime ?t .
    }
    GROUP BY ?entry }
}
