Feature: The matcher's procedure
  How the matcher judges records the same: which records it takes, in what order, by which rules, and what it writes.

  Rule: M1. A step's records are those whose first revision came from that step's import or entry session
    A step's records are those whose first revision, the one with no prov:wasRevisionOf, was generated by
    (prov:wasGeneratedBy) the import or entry session that step made. The matcher is given that activity; it reads no
    file name and no list of steps. A record of the subject's with no one first revision fails the run.

    No example can tell this from taking the records whose first revision's file the step wrote, since in a pod that
    follows these rules the two always agree. Each runtime tests it itself.

    Example: a run takes only the records its step brought, so the import's two codeine records are never judged together
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then that step wrote these matcher judgments:
        | justification    | members                                                                                                  |
        | same code        | allergy RxNorm 10180 from sulfa, allergy RxNorm 10180 from draft 0                                       |
        | same code        | allergy RxNorm 1191 from draft 1, allergy RxNorm 1191 from draft 3                                       |
        | same code        | allergy RxNorm 1191 from draft 1, allergy RxNorm 1191 from draft 2, allergy RxNorm 1191 from draft 3     |
        | same mapped code | allergy RxNorm 7980 from draft 4, allergy SNOMED 373270004                                               |
        | same code        | allergy RxNorm 7980 from draft 4, allergy RxNorm 7980 from draft 5                                       |
        | same mapped code | allergy RxNorm 7980 from draft 5, allergy SNOMED 373270004                                               |
        | same code        | allergy RxNorm 2670 from codeine-1, allergy RxNorm 2670 from codeine-2, allergy RxNorm 2670 from draft 8 |

  Rule: M2. The matcher takes only the subject's records
    Those queries/v1-draft/derivations/subjects.rq gives the pod's rec:Subject, under the everyday lens.

    Example: a record whose patient no About claims, or which names no patient, is never taken nor compared
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then the matcher has no judgment holding allergy RxNorm 10180 from sulfa-other, allergy RxNorm 10180 from draft 6 and allergy RxNorm 10180 from draft 7

    Example: while an About claims a profile the matcher takes its records, and once it is retracted, none
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-r" on 2026-03-04 at 07:00
      And Cleo enters "second-entry" on 2026-03-04 at 08:00
      And the matcher runs on the records of that entry on 2026-03-04 at 08:01
      And Cleo files the judgment "retract-about-r" on 2026-03-04 at 12:00
      And Cleo enters "third-entry" on 2026-03-05 at 08:00
      When the matcher runs on the records of that entry on 2026-03-05 at 08:01
      Then the matcher's judgments holding allergy RxNorm 8591 from draft 0 of "second-entry", allergy RxNorm 8591 from draft 1 of "second-entry" and allergy RxNorm 8591 from draft 0 of "third-entry" are:
        | justification | members                                                                                                | at                  |
        | same code     | allergy RxNorm 8591 from draft 0 of "second-entry", allergy RxNorm 8591 from draft 1 of "second-entry" | 2026-03-04 at 08:01 |

  Rule: M3. It takes them in order of arrival, then by record name
    Arrival is the first revision's prov:generatedAtTime, compared as a time. All of one step's records arrive at the
    step's start (N4), so the record name decides among them. It compares each with the subject's other records, then
    adds it to them for the next.

    No example can tell ordering by record name from ordering by file path, since a record's file is named from its name
    (N9) in its kind's folder and no comparison joins two kinds; this example pins what the order does.

    Example: three records of one code are two judgments, each record compared with those taken before it
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then the matcher's judgments holding allergy RxNorm 1191 from draft 1, allergy RxNorm 1191 from draft 2 and allergy RxNorm 1191 from draft 3 are:
        | justification | members                                                                                              |
        | same code     | allergy RxNorm 1191 from draft 1, allergy RxNorm 1191 from draft 3                                   |
        | same code     | allergy RxNorm 1191 from draft 1, allergy RxNorm 1191 from draft 2, allergy RxNorm 1191 from draft 3 |

  Rule: M4. Each row of the rule list runs its comparison query
    For each row of the current rule list, the matcher runs the query the row names, over the pod, its derived state
    under the everyday lens, and the rows of the current version of the table the row names. A row (record, other) of
    its answer is a match when the record's kind is one the row applies to.

    - R1, jdg:SameCode: queries/v1-draft/matcher/same-code.rq.
    - R2, jdg:SameCodeAndDate: queries/v1-draft/matcher/same-code-and-date.rq.
    - R3, jdg:SameMappedCode: queries/v1-draft/matcher/same-mapped-code.rq, with the ingredient map.
    - R4, jdg:SameMappedCodeAndDate: queries/v1-draft/matcher/same-mapped-code-and-date.rq, with the vaccine group table.

    Background:
      Given a new pod for Dev on 2026-04-01 at 09:00
      And Dev enters "pairs" on 2026-04-02 at 09:00
      And the matcher runs on the records of that entry on 2026-04-02 at 09:05

    Example: two allergies with one code are the same by code, and one with another code joins neither
      Then the matcher's judgments holding allergy RxNorm 10180 from draft 0, allergy RxNorm 10180 from draft 1 and allergy RxNorm 2670 are:
        | justification | members                                                              |
        | same code     | allergy RxNorm 10180 from draft 0, allergy RxNorm 10180 from draft 1 |

    Example: two procedures of one code are the same by code whatever their dates
      Then the matcher's judgments holding procedure SNOMED 73761001 from draft 3 and procedure SNOMED 73761001 from draft 4 are:
        | justification | members                                                                        |
        | same code     | procedure SNOMED 73761001 from draft 3, procedure SNOMED 73761001 from draft 4 |

    Example: two immunizations of one CVX code on one date are the same by code and date, and one on another date joins neither
      Then the matcher's judgments holding immunization CVX 150 from draft 5, immunization CVX 150 from draft 6 and immunization CVX 150 from draft 7 are:
        | justification      | members                                                              |
        | same code and date | immunization CVX 150 from draft 5, immunization CVX 150 from draft 6 |

    Example: two immunizations of different codes in one vaccine group on one date are the same by mapped code and date
      A third on another date joins none, and a fourth of the first's code on its date is the same as it by code and date.

      Then the matcher's judgments holding immunization CVX 141 from draft 8, immunization CVX 150 from draft 9, immunization CVX 141 from draft 10 and immunization CVX 141 from draft 11 are:
        | justification             | members                                                               |
        | same mapped code and date | immunization CVX 141 from draft 8, immunization CVX 150 from draft 9  |
        | same mapped code and date | immunization CVX 150 from draft 9, immunization CVX 141 from draft 11 |
        | same code and date        | immunization CVX 141 from draft 8, immunization CVX 141 from draft 11 |

    Example: codes are mapped by the current version of the ingredient map only
      A pair the old version maps is not mapped once the new one arrives, and a pair only the new one maps is mapped only
      then.

      Given version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-04-03 at 09:00
      And Dev enters "later" on 2026-04-04 at 09:00
      When the matcher runs on the records of that entry on 2026-04-04 at 09:05
      Then the matcher's judgments holding allergy SNOMED 373270004, allergy RxNorm 7980 from draft 13 of "pairs", allergy SNOMED 91936005, allergy RxNorm 733 from draft 15 of "pairs", allergy RxNorm 7980 from draft 0 of "later" and allergy RxNorm 733 from draft 1 of "later" are:
        | justification    | members                                                                                   | at                  |
        | same mapped code | allergy RxNorm 7980 from draft 13 of "pairs", allergy SNOMED 373270004                    | 2026-04-02 at 09:05 |
        | same code        | allergy RxNorm 7980 from draft 0 of "later", allergy RxNorm 7980 from draft 13 of "pairs" | 2026-04-04 at 09:05 |
        | same code        | allergy RxNorm 733 from draft 1 of "later", allergy RxNorm 733 from draft 15 of "pairs"   | 2026-04-04 at 09:05 |
        | same mapped code | allergy RxNorm 733 from draft 1 of "later", allergy SNOMED 91936005                       | 2026-04-04 at 09:05 |

  Rule: M5. It writes one judgment per record per rule that matched anything
    The judgment's members are the record and everything it matched. It is jdg:Same with the rule's justification. It
    uses the rule list's version, the table's version and each member's current version. It is attributed to the
    matcher, at the run's time.

    Background:
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      And the matcher runs on the records of that entry on 2026-03-03 at 08:01

    Example: a record matching under two rules gets a judgment for each, holding it and everything it matched by that rule
      Then the matcher's judgments holding allergy RxNorm 7980 from draft 4 and allergy RxNorm 7980 from draft 5 are:
        | justification    | members                                                            |
        | same mapped code | allergy RxNorm 7980 from draft 4, allergy SNOMED 373270004         |
        | same code        | allergy RxNorm 7980 from draft 4, allergy RxNorm 7980 from draft 5 |
        | same mapped code | allergy RxNorm 7980 from draft 5, allergy SNOMED 373270004         |

    Example: a judgment is a Same of its rule, using the rule list's version, the table's and its members', at the run's time
      Then the matcher's judgments holding allergy SNOMED 373270004 are:
        | justification    | members                                                    | at                  | used                                                                                                                                                                |
        | same mapped code | allergy RxNorm 7980 from draft 4, allergy SNOMED 373270004 | 2026-03-03 at 08:01 | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 1, version 1 of allergy RxNorm 7980 from draft 4, version 1 of allergy SNOMED 373270004 |
        | same mapped code | allergy RxNorm 7980 from draft 5, allergy SNOMED 373270004 | 2026-03-03 at 08:01 | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 1, version 1 of allergy RxNorm 7980 from draft 5, version 1 of allergy SNOMED 373270004 |

  Rule: M6. The matcher reads no person's Same or Different

    Example: the matcher joins the pair a person called different, and not the pair a person called the same
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo files the judgment "persons-different" on 2026-03-02 at 12:00
      And Cleo files the judgment "persons-same" on 2026-03-02 at 12:05
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then the matcher's judgments holding allergy RxNorm 10180 from sulfa, allergy RxNorm 10180 from draft 0, allergy RxNorm 2670 from codeine-1 and allergy RxNorm 5640 are:
        | justification | members                                                                                                  |
        | same code     | allergy RxNorm 10180 from sulfa, allergy RxNorm 10180 from draft 0                                       |
        | same code     | allergy RxNorm 2670 from codeine-1, allergy RxNorm 2670 from codeine-2, allergy RxNorm 2670 from draft 8 |

  Rule: M7. A recheck re-runs the rule of each matcher Same that used a since-revised reference version
    Unless the Same was retracted or superseded. It runs on the members that are still the subject's, under the current
    tables, and writes a new judgment if at least two still match.

    Background:
      Given a new pod for Eve on 2026-05-01 at 09:00
      And Eve files the judgment "about-d" on 2026-05-01 at 09:05
      And Eve enters "allergies" on 2026-05-02 at 09:00
      And the matcher runs on the records of that entry on 2026-05-02 at 09:05

    Example: a Same whose members still match under the revised table is judged again
      Given version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 373270004 and allergy RxNorm 7980 are:
        | justification    | members                                       | at                  | name                                          |
        | same mapped code | allergy SNOMED 373270004, allergy RxNorm 7980 | 2026-05-02 at 09:05 | urn:uuid:b300b191-e8c8-849a-864b-ba5074b9b686 |
        | same mapped code | allergy SNOMED 373270004, allergy RxNorm 7980 | 2026-05-05 at 09:00 | urn:uuid:eb8bdcc4-c099-80be-b13a-17c8b6bd0aac |

    Example: a Same a person retracted is not rechecked
      Given Eve files the judgment "retract-b" on 2026-05-03 at 09:00
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 91936005 and allergy RxNorm 733 are:
        | justification    | members                                     | at                  |
        | same mapped code | allergy SNOMED 91936005, allergy RxNorm 733 | 2026-05-02 at 09:05 |

    Example: a Same a person superseded is not rechecked
      Given Eve files the judgment "supersede-c" on 2026-05-03 at 09:05
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 294505008 and allergy RxNorm 2670 are:
        | justification    | members                                       | at                  |
        | same mapped code | allergy SNOMED 294505008, allergy RxNorm 2670 | 2026-05-02 at 09:05 |

    Example: once the About naming their profile is retracted, fewer than two members are the subject's and nothing is written
      Given Eve files the judgment "retract-about-d" on 2026-05-03 at 09:10
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 387207008 and allergy RxNorm 1191 are:
        | justification    | members                                       | at                  |
        | same mapped code | allergy SNOMED 387207008, allergy RxNorm 1191 | 2026-05-02 at 09:05 |

    Example: a recheck writes nothing when fewer than two members still match under the current table
      Given version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 372687004 and allergy RxNorm 723 are:
        | justification    | members                                      | at                  |
        | same mapped code | allergy SNOMED 372687004, allergy RxNorm 723 | 2026-05-02 at 09:05 |

  Rule: M8. A reference version's description is written only if the pod lacks it

    Example: a reference series or version is described only by the first step that finds the pod lacking it
      Given a new pod for Dev on 2026-04-01 at 09:00
      And Dev enters "pairs" on 2026-04-02 at 09:00
      And the matcher runs on the records of that entry on 2026-04-02 at 09:05 (match-pairs)
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-04-03 at 09:00 (new-map)
      And Dev enters "later" on 2026-04-04 at 09:00
      When the matcher runs on the records of that entry on 2026-04-04 at 09:05
      Then "match-pairs" wrote these reference descriptions:
        | reference                                    |
        | Cascade matcher rules                        |
        | Cascade matcher rules version 1              |
        | SNOMED CT to RxNorm ingredient map           |
        | SNOMED CT to RxNorm ingredient map version 1 |
        | CVX vaccine group table                      |
        | CVX vaccine group table version 1            |
      And "new-map" wrote these reference descriptions:
        | reference                                    |
        | SNOMED CT to RxNorm ingredient map version 2 |
      And that step wrote these reference descriptions:
        | reference |

  Rule: M9. If the pod already holds a judgment of that name, nothing is written
    Not even the reference descriptions it would have written. So running again is always safe.

    Background:
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      And the matcher runs on the records of that entry on 2026-03-03 at 08:01

    Example: running the matcher again on the same step writes nothing
      When the matcher runs on the records of "entry" on 2026-03-03 at 09:00
      Then that step wrote no file

    Example: running the matcher again leaves each judgment it made at the time it was first made
      When the matcher runs on the records of "entry" on 2026-03-03 at 09:00
      Then the matcher's judgments holding allergy SNOMED 373270004 are:
        | justification    | members                                                    | at                  |
        | same mapped code | allergy RxNorm 7980 from draft 4, allergy SNOMED 373270004 | 2026-03-03 at 08:01 |
        | same mapped code | allergy RxNorm 7980 from draft 5, allergy SNOMED 373270004 | 2026-03-03 at 08:01 |

  Rule: M10. A table's current version is the one the pod names, and otherwise the one its series ships with
    rec:shipsWith in references.ttl.

    Example: a table's current version is the one its series ships with until the pod names one, though a later one is listed
      Given a new pod for Dev on 2026-04-01 at 09:00
      And Dev enters "pairs" on 2026-04-02 at 09:00
      And the matcher runs on the records of that entry on 2026-04-02 at 09:05
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-04-03 at 09:00
      And Dev enters "later" on 2026-04-04 at 09:00
      When the matcher runs on the records of that entry on 2026-04-04 at 09:05
      Then the matcher's judgments holding allergy SNOMED 373270004 and allergy SNOMED 91936005 are:
        | justification    | members                                                                | used                                                                                                                                                                            | name                                          |
        | same mapped code | allergy RxNorm 7980 from draft 13 of "pairs", allergy SNOMED 373270004 | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 1, version 1 of allergy RxNorm 7980 from draft 13 of "pairs", version 1 of allergy SNOMED 373270004 | urn:uuid:fb04c4d1-c902-86ae-969f-2454e9345ad2 |
        | same mapped code | allergy RxNorm 733 from draft 1 of "later", allergy SNOMED 91936005    | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 2, version 1 of allergy RxNorm 733 from draft 1 of "later", version 1 of allergy SNOMED 91936005    | urn:uuid:74f606fe-da57-8931-9f53-0140e66a9121 |

  Rule: M11. A rule list whose row names a query that does not hash to the row's rec:queryHash refuses the run
    It writes nothing. So does a rule list with a row naming a file outside queries/v1-draft/matcher/, a row without
    exactly one rec:justifiedAs, rec:query and rec:queryHash, or two rows with one justification. A rule list's rows are
    never edited: a changed query is a new version of the rule list, revising the old.

    Example: a run whose rule list gives same-code.rq a hash its bytes do not have is refused, though two allergies share a code
      Given a new pod for Finn on 2026-06-01 at 09:00
      And Finn enters "same-code-entry" on 2026-06-07 at 09:00
      When the matcher runs on the records of that entry on 2026-06-07 at 09:05
      Then that step is refused
      And that step wrote no file
