Feature: The matcher's procedure
  How the matcher judges records the same: which records it takes, in what order, by which rules, and what it writes.

  Each pod starts empty, at https://pod.example/, with one person as its subject (scripted-input/people.ttl). Cleo
  claims her hospital profile with an About, imports five allergies, enters ten more by hand, and judges some herself.
  Dev enters pairs of allergies, procedures and flu shots for the matcher to compare, and later two more allergies.
  Eve enters ten allergies whose codes the ingredient map pairs, and retracts or supersedes some of the matcher's
  Sames, and once retracts her own supersession. Finn brings exports and entries a runtime must refuse, and two
  allergies of one code. Gus enters medications and lab results, and three flu shots, under the rule list's version 2.
  Hana enters nine conditions, whose codes recur, under the rule list's version 4.

  Rule: M1. A step's records are those whose first revision came from that step's import or entry session
    A step's records are those whose first revision, the one with no prov:wasRevisionOf, was generated by
    (prov:wasGeneratedBy) the import or entry session that step made. The matcher is given that activity; it reads no
    file name and no list of steps. A record of the subject's with no one first revision fails the run. An open takes
    instead the records of the pairs its tables newly join (O1).

    No example can tell this from taking the records whose first revision's file the step wrote, since in a pod that
    follows these rules the two always agree. Each runtime tests it itself.

    Example: a run takes only the records its step brought, so the import's two codeine records are never judged together
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then that step wrote these matcher judgments:
        | justification    | members                                                                                                         |
        | same code        | allergy RxNorm 10180 from sulfa, allergy RxNorm 10180 "Gantanol"                                                |
        | same code        | allergy RxNorm 1191 "Aspirin", allergy RxNorm 1191 "Ecotrin"                                                    |
        | same code        | allergy RxNorm 1191 "Aspirin", allergy RxNorm 1191 "Bayer aspirin", allergy RxNorm 1191 "Ecotrin"               |
        | same mapped code | allergy RxNorm 7980 "Penicillin G", allergy SNOMED 373270004                                                    |
        | same code        | allergy RxNorm 7980 "Penicillin G", allergy RxNorm 7980 "Bicillin"                                              |
        | same mapped code | allergy RxNorm 7980 "Bicillin", allergy SNOMED 373270004                                                        |
        | same code        | allergy RxNorm 2670 from codeine-1, allergy RxNorm 2670 from codeine-2, allergy RxNorm 2670 "Codeine phosphate" |

  Rule: M2. The matcher takes only the subject's records
    Those queries/v1-draft/derivations/subjects.rq gives the pod's rec:Subject, under the everyday lens.

    Example: a record whose patient no About claims, or which names no patient, is never taken nor compared
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then the matcher has no judgment holding allergy RxNorm 10180 from sulfa-other, allergy RxNorm 10180 "Septra" and allergy RxNorm 10180 "Bactrim"

    Example: while an About claims a profile the matcher takes its records, and once it is retracted, none
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-r" on 2026-03-04 at 07:00
      And Cleo enters "second-entry" on 2026-03-04 at 08:00
      And the matcher runs on the records of that entry on 2026-03-04 at 08:01
      And Cleo files the judgment "retract-about-r" on 2026-03-04 at 12:00
      And Cleo enters "third-entry" on 2026-03-05 at 08:00
      When the matcher runs on the records of that entry on 2026-03-05 at 08:01 (match-third-entry)
      Then the matcher's judgments holding allergy RxNorm 8591 "Latex gloves", allergy RxNorm 8591 "Latex" and allergy RxNorm 8591 "Natural rubber latex" are:
        | justification | members                                                         | at                  |
        | same code     | allergy RxNorm 8591 "Latex gloves", allergy RxNorm 8591 "Latex" | 2026-03-04 at 08:01 |

  Rule: M3. It takes them in order of arrival, then by record name
    Arrival is the first revision's prov:generatedAtTime, compared as a time. All of one step's records arrive at the
    step's start (N4), so the record name decides among them. It compares each with the subject's other records, then
    adds it to them for the next.

    No example can tell ordering by record name from ordering by file path, since a record's file is named from its name
    (N9) in its kind's folder and no comparison joins two kinds; this example pins what the order does.

    Example: three records of one code are two judgments, each record compared with those taken before it
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then the matcher's judgments holding allergy RxNorm 1191 "Aspirin", allergy RxNorm 1191 "Bayer aspirin" and allergy RxNorm 1191 "Ecotrin" are:
        | justification | members                                                                                           |
        | same code     | allergy RxNorm 1191 "Aspirin", allergy RxNorm 1191 "Ecotrin"                                      |
        | same code     | allergy RxNorm 1191 "Aspirin", allergy RxNorm 1191 "Bayer aspirin", allergy RxNorm 1191 "Ecotrin" |

  Rule: M4. Each row of the rule list runs its comparison query
    For each row of the current rule list, the matcher runs the query the row names, over the pod, its derived state
    under the everyday lens, and, for a row naming a table kind (rec:tableKind), the rows of the current version of
    every series of that kind (M13). A row (record, other) of its answer, with the version whose rows joined it as
    ?origin when the rule reads a table, is a match when the record's kind is one the row applies to.

    A query reads a table's rows only inside GRAPH ?origin, guarded by ?origin prov:specializationOf/rec:tableKind
    and its kind. A record's code joins a row by the code's IRI, one form per code system (rec:CodeSystem in
    records.ttl): a code written as a literal, as health:vaccineCode "141", is its system's void:uriSpace followed
    by the literal as written, <http://hl7.org/fhir/sid/cvx/141>.

    - R1, jdg:SameCode: queries/v1-draft/matcher/same-code.rq.
    - R2, jdg:SameCodeAndDate: queries/v1-draft/matcher/same-code-and-date.rq.
    - R3, jdg:SameMappedCode: in the stories' lists, queries/v1-draft/matcher/same-mapped-code.rq, with
      rec:SubstanceIngredients, a kind only the stories fill; in the vocabulary's list from its version 2,
      queries/v1-draft/matcher/same-ingredient.rq, with rec:ProductIngredients, for allergies only. A justification is
      one row of a list's version, so a judgment still says which query ran.
    - R4, jdg:SameMappedCodeAndDate: queries/v1-draft/matcher/same-mapped-code-and-date.rq, with rec:VaccineGroups.

    Version 2 of the rule list adds two rows, whose examples are under M12:

    - R5, jdg:SameMedicationCode: queries/v1-draft/matcher/same-medication-code.rq.
    - R6, jdg:SameResult: queries/v1-draft/matcher/same-result.rq.

    Version 3 of the vocabulary's list adds one row, whose examples are under O1:

    - R7, jdg:SameConvertedCode: queries/v1-draft/matcher/same-converted-code.rq, with rec:CodeConversions, for
      conditions only. A record coded with a retired code is the same as one coded with the one code it converts to;
      a code split into several has no row, since one judgment holds a record and all it matched.

    Version 4 of the vocabulary's list adds one row, whose examples are under M14 and O1, and takes conditions out of R1:

    - R8, jdg:SameCodeAndPeriod: queries/v1-draft/matcher/same-code-and-period.rq, for conditions only. Two conditions
      of one ICD-10-CM or SNOMED CT code are the same when their periods overlap.

    Version 5 of the vocabulary's list changes R7's query, whose example is under O1:

    - R7, jdg:SameConvertedCode: queries/v1-draft/matcher/same-one-to-one-conversion.rq, with rec:CodeConversions. A
      retired code and its replacement are joined only by a dct:isReplacedBy row whose cardinality is 1:1. A split
      (1:n), a merge (n:1) and an n:n row join nothing, and neither does a row of the earlier form, skos:exactMatch
      with no cardinality, which same-converted-code.rq in versions 3 and 4 reads.

    The vocabulary's own rule list, runtime/rule-list/, is the one an app uses: R1, R2, R4, R5 and R6 in its version 1,
    R3 as well in its version 2, whose examples are under O1, R7 as well in its version 3, R8 as well in its
    version 4, where R1 applies to allergies and procedures only, and R7's new query in its version 5.

    Background:
      Given a new pod for Dev on 2026-04-01 at 09:00
      And Dev enters "pairs" on 2026-04-02 at 09:00
      And the matcher runs on the records of that entry on 2026-04-02 at 09:05

    Example: two allergies with one code are the same by code, and one with another code joins neither
      Then the matcher's judgments holding allergy RxNorm 10180 "Sulfamethoxazole", allergy RxNorm 10180 "Bactrim" and allergy RxNorm 2670 are:
        | justification | members                                                                 |
        | same code     | allergy RxNorm 10180 "Sulfamethoxazole", allergy RxNorm 10180 "Bactrim" |

    Example: two procedures of one code are the same by code whatever their dates
      Then the matcher's judgments holding procedure SNOMED 73761001 "Colonoscopy" and procedure SNOMED 73761001 "Screening colonoscopy" are:
        | justification | members                                                                                    |
        | same code     | procedure SNOMED 73761001 "Colonoscopy", procedure SNOMED 73761001 "Screening colonoscopy" |

    Example: two immunizations of one CVX code on one date are the same by code and date, and one on another date joins neither
      Then the matcher's judgments holding immunization CVX 150 "Fluzone", immunization CVX 150 "Afluria" and immunization CVX 150 "Flucelvax" are:
        | justification      | members                                                        |
        | same code and date | immunization CVX 150 "Fluzone", immunization CVX 150 "Afluria" |

    Example: two immunizations of different codes in one vaccine group on one date are the same by mapped code and date
      A third on another date joins none, and a fourth of the first's code on its date is the same as it by code and date.

      Then the matcher's judgments holding immunization CVX 141 "Fluarix", immunization CVX 150 "FluLaval", immunization CVX 141 "Flublok" and immunization CVX 141 "Fluad" are:
        | justification             | members                                                         |
        | same mapped code and date | immunization CVX 141 "Fluarix", immunization CVX 150 "FluLaval" |
        | same mapped code and date | immunization CVX 150 "FluLaval", immunization CVX 141 "Fluad"   |
        | same code and date        | immunization CVX 141 "Fluarix", immunization CVX 141 "Fluad"    |

    Example: codes are mapped by the current version of the ingredient map only
      A pair the old version maps is not mapped once the new one arrives, and a pair only the new one maps is mapped only
      then.

      Given version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-04-03 at 09:00
      And Dev enters "later" on 2026-04-04 at 09:00
      When the matcher runs on the records of that entry on 2026-04-04 at 09:05 (match-later)
      Then the matcher's judgments holding allergy SNOMED 373270004, allergy RxNorm 7980 "Penicillin G", allergy SNOMED 91936005, allergy RxNorm 733 "Ampicillin", allergy RxNorm 7980 "Bicillin" and allergy RxNorm 733 "Principen" are:
        | justification    | members                                                            | at                  |
        | same mapped code | allergy RxNorm 7980 "Penicillin G", allergy SNOMED 373270004       | 2026-04-02 at 09:05 |
        | same code        | allergy RxNorm 7980 "Bicillin", allergy RxNorm 7980 "Penicillin G" | 2026-04-04 at 09:05 |
        | same code        | allergy RxNorm 733 "Principen", allergy RxNorm 733 "Ampicillin"    | 2026-04-04 at 09:05 |
        | same mapped code | allergy RxNorm 733 "Principen", allergy SNOMED 91936005            | 2026-04-04 at 09:05 |

  Rule: M5. It writes one judgment per record per rule, and per table version, that matched anything
    The judgment's members are the record and everything that version's rows matched it with, or everything the rule
    matched it with when the rule reads no table. It is jdg:Same with the rule's justification. It uses the rule
    list's version, the table version whose rows joined it, if any, and each member's current version. It is
    attributed to the matcher, at the run's time.

    Background:
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      And the matcher runs on the records of that entry on 2026-03-03 at 08:01

    Example: a record matching under two rules gets a judgment for each, holding it and everything it matched by that rule
      Then the matcher's judgments holding allergy RxNorm 7980 "Penicillin G" and allergy RxNorm 7980 "Bicillin" are:
        | justification    | members                                                            |
        | same mapped code | allergy RxNorm 7980 "Penicillin G", allergy SNOMED 373270004       |
        | same code        | allergy RxNorm 7980 "Penicillin G", allergy RxNorm 7980 "Bicillin" |
        | same mapped code | allergy RxNorm 7980 "Bicillin", allergy SNOMED 373270004           |

    Example: a judgment is a Same of its rule, using the rule list's version, the table's and its members', at the run's time
      Then the matcher's judgments holding allergy SNOMED 373270004 are:
        | justification    | members                                                      | at                  | used                                                                                                                                                                  |
        | same mapped code | allergy RxNorm 7980 "Penicillin G", allergy SNOMED 373270004 | 2026-03-03 at 08:01 | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 1, version 1 of allergy RxNorm 7980 "Penicillin G", version 1 of allergy SNOMED 373270004 |
        | same mapped code | allergy RxNorm 7980 "Bicillin", allergy SNOMED 373270004     | 2026-03-03 at 08:01 | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 1, version 1 of allergy RxNorm 7980 "Bicillin", version 1 of allergy SNOMED 373270004     |

  Rule: M6. The matcher reads no person's Same or Different

    Example: the matcher joins the pair a person called different, and not the pair a person called the same
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo files the judgment "persons-different" on 2026-03-02 at 12:00
      And Cleo files the judgment "persons-same" on 2026-03-02 at 12:05
      And Cleo enters "entry" on 2026-03-03 at 08:00
      When the matcher runs on the records of that entry on 2026-03-03 at 08:01
      Then the matcher's judgments holding allergy RxNorm 10180 from sulfa, allergy RxNorm 10180 "Gantanol", allergy RxNorm 2670 from codeine-1 and allergy RxNorm 5640 are:
        | justification | members                                                                                                         |
        | same code     | allergy RxNorm 10180 from sulfa, allergy RxNorm 10180 "Gantanol"                                                |
        | same code     | allergy RxNorm 2670 from codeine-1, allergy RxNorm 2670 from codeine-2, allergy RxNorm 2670 "Codeine phosphate" |

  Rule: M7. A recheck re-runs the rule of each matcher Same that used a reference version the tables revise
    Unless the Same was retracted, or superseded by a judgment not itself retracted: a retracted judgment supersedes
    nothing. It runs on the members that are still the subject's, under the current version of the series whose
    version the Same used, and writes a new judgment, using that version, if at least two still match. A version is
    revised when a version of the tables revises it, whether or not the pod describes that one, so an open that writes
    the descriptions last (W1) still rechecks. A Same whose rule now reads a table, and which used no version of
    that table's kind, is not filed again. A Same whose rule the current rule list lacks refuses the recheck.

    Background:
      Given a new pod for Eve on 2026-05-01 at 09:00
      And Eve files the judgment "about-d" on 2026-05-01 at 09:05
      And Eve enters "allergies" on 2026-05-02 at 09:00
      And the matcher runs on the records of that entry on 2026-05-02 at 09:05

    Example: a Same whose members still match under the revised table is judged again
      Given version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 373270004 and allergy RxNorm 7980 are:
        | justification    | members                                       | at                  | name                                          |
        | same mapped code | allergy SNOMED 373270004, allergy RxNorm 7980 | 2026-05-02 at 09:05 | urn:uuid:b300b191-e8c8-849a-864b-ba5074b9b686 |
        | same mapped code | allergy SNOMED 373270004, allergy RxNorm 7980 | 2026-05-05 at 09:00 | urn:uuid:eb8bdcc4-c099-80be-b13a-17c8b6bd0aac |

    Example: a Same a person retracted is not rechecked
      Given Eve files the judgment "retract-b" on 2026-05-03 at 09:00
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 91936005 and allergy RxNorm 733 are:
        | justification    | members                                     | at                  |
        | same mapped code | allergy SNOMED 91936005, allergy RxNorm 733 | 2026-05-02 at 09:05 |

    Example: a Same a person superseded is not rechecked
      Given Eve files the judgment "supersede-c" on 2026-05-03 at 09:05
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 294505008 and allergy RxNorm 2670 are:
        | justification    | members                                       | at                  |
        | same mapped code | allergy SNOMED 294505008, allergy RxNorm 2670 | 2026-05-02 at 09:05 |

    Example: a Same whose superseding judgment a person retracted is rechecked
      Given Eve files the judgment "supersede-c" on 2026-05-03 at 09:05
      And Eve files the judgment "retract-supersede-c" on 2026-05-03 at 09:15
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 294505008 and allergy RxNorm 2670 are:
        | justification    | members                                       | at                  |
        | same mapped code | allergy SNOMED 294505008, allergy RxNorm 2670 | 2026-05-02 at 09:05 |
        | same mapped code | allergy SNOMED 294505008, allergy RxNorm 2670 | 2026-05-05 at 09:00 |

    Example: once the About naming their profile is retracted, fewer than two members are the subject's and nothing is written
      Given Eve files the judgment "retract-about-d" on 2026-05-03 at 09:10
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 387207008 and allergy RxNorm 1191 are:
        | justification    | members                                       | at                  |
        | same mapped code | allergy SNOMED 387207008, allergy RxNorm 1191 | 2026-05-02 at 09:05 |

    Example: a recheck writes nothing when fewer than two members still match under the current table
      Given version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-05-04 at 09:00
      When the matcher rechecks on 2026-05-05 at 09:00
      Then the matcher's judgments holding allergy SNOMED 372687004 and allergy RxNorm 723 are:
        | justification    | members                                      | at                  |
        | same mapped code | allergy SNOMED 372687004, allergy RxNorm 723 | 2026-05-02 at 09:05 |

  Rule: M8. A reference version's description is written only if the pod lacks it

    Example: a reference series or version is described only by the first step that finds the pod lacking it
      Given a new pod for Dev on 2026-04-01 at 09:00
      And Dev enters "pairs" on 2026-04-02 at 09:00
      And the matcher runs on the records of that entry on 2026-04-02 at 09:05 (match-pairs)
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-04-03 at 09:00 (new-map)
      And Dev enters "later" on 2026-04-04 at 09:00
      When the matcher runs on the records of that entry on 2026-04-04 at 09:05
      Then "match-pairs" wrote these reference descriptions:
        | reference                                    |
        | Cascade matcher rules                        |
        | Cascade matcher rules version 1              |
        | SNOMED CT to RxNorm ingredient map           |
        | SNOMED CT to RxNorm ingredient map version 1 |
        | CVX vaccine group table                      |
        | CVX vaccine group table version 1            |
      And "new-map" wrote these reference descriptions:
        | reference                                    |
        | SNOMED CT to RxNorm ingredient map version 2 |
      And that step wrote these reference descriptions:
        | reference |

  Rule: M9. If the pod already holds a judgment of that name, it is not written again
    Only the reference descriptions it uses that the pod lacks are written (M8), so a run that stopped between its
    judgments and its descriptions (W1) finishes when run again. So running again is always safe.

    Background:
      Given a new pod for Cleo on 2026-03-01 at 09:00
      And Cleo files the judgment "about-p" on 2026-03-01 at 09:05
      And the export "first-export" is imported on 2026-03-02 at 10:00
      And Cleo enters "entry" on 2026-03-03 at 08:00
      And the matcher runs on the records of that entry on 2026-03-03 at 08:01

    Example: running the matcher again on the same step writes nothing
      When the matcher runs on the records of "entry" on 2026-03-03 at 09:00 (again)
      Then that step wrote no file

    Example: running the matcher again leaves each judgment it made at the time it was first made
      When the matcher runs on the records of "entry" on 2026-03-03 at 09:00 (again)
      Then the matcher's judgments holding allergy SNOMED 373270004 are:
        | justification    | members                                                      | at                  |
        | same mapped code | allergy RxNorm 7980 "Penicillin G", allergy SNOMED 373270004 | 2026-03-03 at 08:01 |
        | same mapped code | allergy RxNorm 7980 "Bicillin", allergy SNOMED 373270004     | 2026-03-03 at 08:01 |

  Rule: M10. A table's current version is the one the pod names, and otherwise its series' default
    In a story, the default is the version the story's tables ship with (rec:shipsWith). In an app, it is
    the newest version of the series the app holds: the end of its line of prov:wasRevisionOf. An app never adopts a
    version that does not descend from the one it holds. The examples run on stories, so none shows an app's default.

    Example: a table's current version is the one its series ships with until the pod names one, though a later one is listed
      Given a new pod for Dev on 2026-04-01 at 09:00
      And Dev enters "pairs" on 2026-04-02 at 09:00
      And the matcher runs on the records of that entry on 2026-04-02 at 09:05
      And version "2" of "SNOMED CT to RxNorm ingredient map" arrives on 2026-04-03 at 09:00
      And Dev enters "later" on 2026-04-04 at 09:00
      When the matcher runs on the records of that entry on 2026-04-04 at 09:05 (match-later)
      Then the matcher's judgments holding allergy SNOMED 373270004 and allergy SNOMED 91936005 are:
        | justification    | members                                                      | used                                                                                                                                                                  | name                                          |
        | same mapped code | allergy RxNorm 7980 "Penicillin G", allergy SNOMED 373270004 | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 1, version 1 of allergy RxNorm 7980 "Penicillin G", version 1 of allergy SNOMED 373270004 | urn:uuid:fb04c4d1-c902-86ae-969f-2454e9345ad2 |
        | same mapped code | allergy RxNorm 733 "Principen", allergy SNOMED 91936005      | Cascade matcher rules version 1, SNOMED CT to RxNorm ingredient map version 2, version 1 of allergy RxNorm 733 "Principen", version 1 of allergy SNOMED 91936005      | urn:uuid:f53228db-f86e-885e-977c-53f3ba48aabd |

  Rule: M11. A rule list whose row names a query that does not hash to the row's rec:queryHash refuses the run
    It writes nothing. So does a rule list with a row naming a file outside queries/v1-draft/matcher/, a row without
    exactly one rec:justifiedAs, rec:query and rec:queryHash, or two rows with one justification. A rule list's rows are
    never edited: a changed query is a new version of the rule list, revising the old. The stories' rule lists are
    fixtures, and move with the vocabulary's queries; a rule list an app has used never changes.

    Example: a run whose rule list gives same-code.rq a hash its bytes do not have is refused, though two allergies share a code
      Given a new pod for Finn on 2026-06-01 at 09:00
      And Finn enters "same-code-entry" on 2026-06-07 at 09:00
      When the matcher runs on the records of that entry on 2026-06-07 at 09:05
      Then that step is refused
      And that step wrote no file

  Rule: M12. A medication is compared by its RxNorm code, and a lab result by its LOINC code, its time and its value
    R5 joins two medications of one RxNorm code, whether each came from a prescription or from a list of what the
    person takes. R6 joins two lab results of one LOINC code, one time and one value: a time is compared as a time, so
    one instant written in two time zones is one time, and units are not compared, as sources spell them differently.

    Background:
      Given a new pod for Gus on 2025-05-01 at 09:00
      And Gus enters "medicines-and-results" on 2025-05-02 at 09:00
      And the matcher runs on the records of that entry on 2025-05-02 at 09:05

    Example: a prescription and a list entry of one RxNorm code are the same medication, and one of another code joins neither
      Then the matcher's judgments holding medication RxNorm 314076 "lisinopril 10 MG Oral Tablet", medication RxNorm 314076 "Lisinopril 10 mg tablet" and medication RxNorm 197361 are:
        | justification        | members                                                                                                     | used                                                                                                                                                                   |
        | same medication code | medication RxNorm 314076 "lisinopril 10 MG Oral Tablet", medication RxNorm 314076 "Lisinopril 10 mg tablet" | Cascade matcher rules version 2, version 1 of medication RxNorm 314076 "lisinopril 10 MG Oral Tablet", version 1 of medication RxNorm 314076 "Lisinopril 10 mg tablet" |

    Example: two lab results of one code, one instant in two time zones and one value are the same result, and one at another time or of another value joins neither
      Then the matcher's judgments holding lab result LOINC 2823-3 "Potassium", lab result LOINC 2823-3 "Serum potassium", lab result LOINC 2823-3 "Potassium in April" and lab result LOINC 2823-3 "Potassium repeat" are:
        | justification | members                                                                        | used                                                                                                                                     |
        | same result   | lab result LOINC 2823-3 "Potassium", lab result LOINC 2823-3 "Serum potassium" | Cascade matcher rules version 2, version 1 of lab result LOINC 2823-3 "Potassium", version 1 of lab result LOINC 2823-3 "Serum potassium" |

  Rule: M13. A match comes from one table version's rows, and each version that joins a pair gives a judgment of its own
    A rule naming a table kind reads the rows of the current version of every series of that kind, each in the graph
    named by the version's IRI, and the descriptions of those versions and their series, as references.ttl states
    them, beside the pod. A comparison reads rows only inside GRAPH ?origin, so it joins rows of one version only, and
    the judgment uses that version. Rows never reach the pod.

    Gus's references hold a second vaccine group series, "Clinic vaccine groups", that also puts CVX 140 in the
    influenza group. M3 takes his three shots in the order 140, 150, 141.

    Example: two tables of one kind that both join a pair each give a judgment of it, and a pair only one joins gets one
      Given a new pod for Gus on 2025-05-01 at 09:00
      And Gus enters "flu-shots" on 2025-10-02 at 09:00
      When the matcher runs on the records of that entry on 2025-10-02 at 09:05
      Then the matcher's judgments holding immunization CVX 141 "Fluarix", immunization CVX 150 "FluLaval" and immunization CVX 140 "Afluria" are:
        | justification             | members                                                                                          | used                                                                                                                                                                                  |
        | same mapped code and date | immunization CVX 141 "Fluarix", immunization CVX 150 "FluLaval"                                  | Cascade matcher rules version 2, CVX vaccine group table version 1, version 1 of immunization CVX 141 "Fluarix", version 1 of immunization CVX 150 "FluLaval"                         |
        | same mapped code and date | immunization CVX 140 "Afluria", immunization CVX 150 "FluLaval" | Cascade matcher rules version 2, Clinic vaccine groups version 1, version 1 of immunization CVX 140 "Afluria", version 1 of immunization CVX 150 "FluLaval" |
        | same mapped code and date | immunization CVX 140 "Afluria", immunization CVX 141 "Fluarix", immunization CVX 150 "FluLaval" | Cascade matcher rules version 2, Clinic vaccine groups version 1, version 1 of immunization CVX 140 "Afluria", version 1 of immunization CVX 141 "Fluarix", version 1 of immunization CVX 150 "FluLaval" |

  Rule: M14. A condition is compared by its code and its period
    R8 joins two conditions of one ICD-10-CM or SNOMED CT code whose periods overlap. A period runs from the onset's
    day to the abatement's day. An abatement that is not a date, or falls before the onset, counts as none. With none,
    the period runs on while the status is active, recurrence or relapse, and is the onset's day alone otherwise
    (resolved, inactive, remission, or no status). A day is the first ten characters of the date as written, so a date
    and a dateTime compare, and a time zone never moves a day, unlike R6's instants. Both bounds count. A condition
    with no onset joins nothing. So a condition two sources both call active joins whatever onsets they give, and two
    episodes that are each over, and apart, do not.

    Hana's "episodes" are conditions of J18.9 (three), E11.9 (two), R10.9 (two) and SNOMED CT 195662009 (two).

    Background:
      Given a new pod for Hana on 2026-07-01 at 09:00
      And the pod is opened with the tables "app-periods" on 2026-07-01 at 09:01
      And Hana enters "episodes" on 2026-07-02 at 09:00
      And the matcher runs on the records of that entry on 2026-07-02 at 09:05

    Example: two conditions of one ICD-10-CM code whose periods overlap are the same by code and period, and one of a later episode joins neither
      Then the matcher's judgments holding condition ICD-10-CM J18.9 "Pneumonia, first report", condition ICD-10-CM J18.9 "Pneumonia, second report" and condition ICD-10-CM J18.9 "Pneumonia, 2024" are:
        | justification        | members                                                                                                       | used                                                                                                                                                                                                                         |
        | same code and period | condition ICD-10-CM J18.9 "Pneumonia, first report", condition ICD-10-CM J18.9 "Pneumonia, second report" | Matcher rules version 4, version 1 of condition ICD-10-CM J18.9 "Pneumonia, first report", version 1 of condition ICD-10-CM J18.9 "Pneumonia, second report" |

    Example: two conditions both active with no abatement are the same by code and period, whatever their onsets
      Then the matcher's judgments holding condition ICD-10-CM E11.9 "Type 2 diabetes, clinic" and condition ICD-10-CM E11.9 "Type 2 diabetes, hospital" are:
        | justification        | members                                                                                       |
        | same code and period | condition ICD-10-CM E11.9 "Type 2 diabetes, clinic", condition ICD-10-CM E11.9 "Type 2 diabetes, hospital" |

    Example: two episodes of one SNOMED CT code that are each over, and apart, join nothing
      Then the matcher has no judgment holding condition SNOMED 195662009 "Acute viral pharyngitis, 2017" and condition SNOMED 195662009 "Acute viral pharyngitis, 2020"

    Example: a condition with no onset joins nothing
      Then the matcher has no judgment holding condition ICD-10-CM R10.9 "Abdominal pain, no onset" and condition ICD-10-CM R10.9 "Abdominal pain, 2022"
