PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?import WHERE {
  ?import a prov:Activity ; rdfs:label ?label ; prov:startedAtTime "2026-01-04T10:00:00Z"^^xsd:dateTime .
}
