PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?predicate ?value WHERE {
  { SELECT DISTINCT ?import ?file WHERE {
    GRAPH <urn:cascade:steps> { <urn:cascade:step:first-export> prov:generated ?file }
    GRAPH ?file { ?import prov:used ?document }
  } }
  GRAPH ?file {
    { ?import ?predicate ?value FILTER (!isBlank(?value)) }
    UNION
    { ?import prov:qualifiedAssociation/prov:hadPlan/rdfs:label ?value BIND(prov:qualifiedAssociation AS ?predicate) }
  }
}
