PREFIX jdg: <https://ns.cascadeprotocol.org/judgments/v1-draft#>
PREFIX rec: <https://ns.cascadeprotocol.org/records/v1-draft#>

SELECT ?judgment
WHERE {
  ?judgment a jdg:Judgment ; rec:counts true .
}
