PREFIX clinical: <https://ns.cascadeprotocol.org/clinical/v1#>
PREFIX health: <https://ns.cascadeprotocol.org/health/v1#>
PREFIX pav: <http://purl.org/pav/>
PREFIX rec: <https://ns.cascadeprotocol.org/records/v1-draft#>

SELECT ?entry
WHERE {
  ?record a health:AllergyRecord ; rec:inEntry ?entry ;
          pav:hasCurrentVersion/clinical:criticality ?c .
}
GROUP BY ?entry
HAVING (COUNT(DISTINCT ?c) > 1)
