PREFIX pav: <http://purl.org/pav/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rec: <https://ns.cascadeprotocol.org/records/v1-draft#>

SELECT ?profile ?profileLabel ?record ?recordLabel
WHERE {
  ?record pav:hasCurrentVersion/rec:patient ?profile .
  OPTIONAL { ?profile rdfs:label ?profileLabel }
  OPTIONAL { ?record rdfs:label ?recordLabel }
}
ORDER BY ?profileLabel ?profile ?recordLabel ?record
